// <auto-generated />
namespace RiggingConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class additionfieldsandlines : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additionfieldsandlines));
        
        string IMigrationMetadata.Id
        {
            get { return "201809250930346_addition-fields-and-lines"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
